---
- name: create system user for node app
  user:
    name: '{{ node_app_user }}'
    shell: /bin/bash
    password: '{{ node_app_user_password }}'
  register: app_system_user
- name: bundle the app files
  local_action:
    module: archive
    path:
      - ../app.js
      - ../Gulpfile.js
      - ../package.json
      - ../src/
    dest: ./{{ app_bundle_name }}
  register: app_bundled
- name: create bundle destination
  file: path=/home/{{ node_app_user }}/app state=directory
  register: dest_created
- name: unpack the app bundle
  unarchive:
    # src: /home/{{ node_app_user }}/{{ app_bundle_name }}
    src: ./{{ app_bundle_name }}
    dest: /home/{{ node_app_user }}/app
    owner: '{{ node_app_user }}'
    list_files: yes
  when: dest_created|success and app_bundled|success
