# Selections from https://github.com/ansible/ansible-examples/blob/master/language_features/postgresql.yml
---
- name: install postgres
  include: 01_postgres_install.yml
  register: postgres_install
- name: create {{ postgres_app_user }} system user
  user:
    name: '{{ postgres_app_user }}'
    shell: /bin/bash
    password: '{{ postgres_app_user_password }}'
  register: app_system_user
- name: config postgres
  become_user: '{{ postgres_admin_user }}'
  include: 02_postgres_config.yml
  when: app_system_user | success
  register: postgres_config
