---
- name: install psycopg2
  apt:
    name: python-psycopg2
    state: present
    update_cache: yes
    cache_valid_time: '{{ apt_cache_time }}'
- name: install postgres
  include: postgres_install.yml
  register: postgres_install
- name: config postgres
  become: yes
  become_user: '{{ postgres_admin_user }}'
  include: postgres_config.yml
  register: postgres_config
- name: create {{ postgres_app_user }} system user
  user: name={{ postgres_app_user }} shell=/bin/bash password={{ postgres_app_user_password }}
  register: app_system_user
